import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Changa } from "next/font/google";
import "./globals.css";

const changa = Changa({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--font-changa",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={changa.className}>{children}</body>
    </html>
  );
}
